site_name: VQGAN JAX/Flax Docs
repo_url: https://github.com/WolodjaZ/jax-vqgan

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Welcome to Docs ğŸ‘‹: index.md
  - Tutorials ğŸ™‡: tutorials.md
  - How-To Guides ğŸ“š: how-to-guides.md
  - reference.md
  - Explanation ğŸ¤¯: explanation.md
  - Changelog â³: changelog.md

watch:
  - .  # reload docs for any file changes
